### ISSUE TITLE
I am getting this error, what might be the issue?

### ISSUE THREAD

**Issue by tinegaharon** [dipakkr/3d-cnn-action-recognition#3]
amax@amax:/media/amax/Masters/Hairen/ActionRecognition/3d-cnn-action-recognition/3d-cnn-action-recognition-master$ python3 3dcnn.py --batch 32 --epoch 50 --videos dataset/ --nclass 10 --output 3dcnnresult/ --color True --skip False --depth 10
/home/amax/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/home/amax/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
  0%|                                                                                                                                                                              | 0/1 [00:00<?, ?it/s]UCF-10
Traceback (most recent call last):
  File "3dcnn.py", line 237, in <module>
    main()
  File "3dcnn.py", line 145, in main
    args.output, args.color, args.skip)
  File "3dcnn.py", line 101, in loaddata
    X.append(vid3d.video3d(v_file_path, color=color, skip=skip))
  File "/media/amax/Masters/Hairen/ActionRecognition/3d-cnn-action-recognition/3d-cnn-action-recognition-master/videoto3d.py", line 29, in video3d
    frame = cv2.resize(frame, (self.height, self.width))
cv2.error: OpenCV(3.4.3) /io/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 11.82it/s]

**Comment by Soufiane-Fartit** [comment]
isn't it supposed to be (frame.height, frame.width)instead of (self.height, self.width) ? and that's why it returns Null.

**Comment by DecentMakeover** [comment]
The image is empty
